### ISSUE TITLE
Corrections needed for weights conversion

### ISSUE THREAD

**Issue by benyv** [zibbini/convnext-v2_tensorflow#1]
Thanks for this repo :)
There are a few corrections needed for the tf model of convnext_v2 to produce similar results to pt model:
1. Use ord='fro' in the tf.norm() [operation](https://github.com/zibbini/convnext-v2_tensorflow/blob/c0da4b0cca91ac4c126ba2103853bbdb9a4d6f93/convnext_tf/convnext_v2.py#L27). torch.norm() with p=2, is actually using the "Frobenius" norm, while in tf it is not.
2. The index for [pwconv2 ](https://github.com/zibbini/convnext-v2_tensorflow/blob/c0da4b0cca91ac4c126ba2103853bbdb9a4d6f93/convert_weights_v2.py#L172) should be 5 instead of 4 (should check for j == 5).
3. Softmax is performed both in tf model [instantiation ](https://github.com/zibbini/convnext-v2_tensorflow/blob/c0da4b0cca91ac4c126ba2103853bbdb9a4d6f93/convnext_tf/convnext_v2.py#L65) and on its [output](https://github.com/zibbini/convnext-v2_tensorflow/blob/c0da4b0cca91ac4c126ba2103853bbdb9a4d6f93/convert_weights_v2.py#L65). One of them should be removed.

Also note, that for the huge models (esp. with large images), the [rtol ](https://github.com/zibbini/convnext-v2_tensorflow/blob/c0da4b0cca91ac4c126ba2103853bbdb9a4d6f93/convert_weights_v2.py#L67) parameter in the comparison should be increased to 3e-3.

**Comment by zibbini** [comment]
Thanks for this - I've added those corrections in the latest commits :)

**Comment by benyv** [comment]
Thanks :)
